### ISSUE TITLE
ModuleNotFoundError

### ISSUE THREAD

**Issue by vcvishal** [sraashis/ature#228]
Traceback (most recent call last):
  File "main.py", line 1, in <module>
    import testarch.unet as net
  File "C:\Users\HI\Desktop\ature-master\testarch\unet\__init__.py", line 14, in <module>
    from utils.measurements import ScoreAccumulator
  File "C:\Users\HI\Desktop\ature-master\utils\measurements.py", line 14, in <module>
    import imgcommons.utils as imgutils
ModuleNotFoundError: No module named 'imgcommons'

**Comment by sraashis** [comment]
Thank you so much for pointing out. It was an unused module. I removed it and should be fine now.

**Comment by vcvishal** [comment]
thank you this problem has resolved
