### ISSUE TITLE
strange output 

### ISSUE THREAD

**Issue by vcvishal** [sraashis/ature#229]
when I run this code the following output is given
C:\Users\HI\Desktop\ature-master>python main.py
Total Params: 31042434
[0, 0, 0, 0]
what is it, how I get the correct output
I am using windows

**Comment by sraashis** [comment]
- Total Params: 31042434 is the number of parameters in UNET. It is printed at the end of  unet/module.py file
- [0, 0, 0, 0] is supposed to be the precision , recall and accuracy on all of the test dataset.  Which I guess is empty in your case. It is at the end of unet/init.py file.

**Comment by vcvishal** [comment]
i am not sure where i am doing wrong would you please help me
path is incorrect?
image not found?
or else?

**Comment by sraashis** [comment]
Just wanted to make sure. Are you trying on DRIVE dataset or your own dataset?

**Comment by vcvishal** [comment]
yes i am using DRIVE

this time 
Total Params: 31042434
### SPLIT FOUND:  data\DRIVE\splits\UNET-DRIVE.json Loaded
### CRITICAL!!! logs\DRIVE\UNET-DRIVE-TEST.csv" already exists.
Override? [Y/N]: y
### CRITICAL!!! logs\DRIVE\UNET-DRIVE-TRAIN.csv" already exists.
Override? [Y/N]: y
### CRITICAL!!! logs\DRIVE\UNET-DRIVE-VAL.csv" already exists.
Override? [Y/N]: y
### GPU not found.
Patches: 135
Patches: 9
Patches: 9
Patches: 9
Patches: 9
Patches: 9
Training...
Traceback (most recent call last):
  File "C:\Users\vcvis\Desktop\ature-master\testarch\unet\__init__.py", line 44, in run
    epoch_run=drive_trainer.epoch_ce_loss)
  File "C:\Users\vcvis\Desktop\ature-master\nbee\torchbee.py", line 82, in train
    epoch_run(epoch=epoch, data_loader=data_loader)
  File "C:\Users\vcvis\Desktop\ature-master\nbee\torchbee.py", line 210, in epoch_ce_loss
    for i, data in enumerate(kw['data_loader'], 1):
  File "D:\miniconda\lib\site-packages\torch\utils\data\dataloader.py", line 819, in __iter__
    return _DataLoaderIter(self)
  File "D:\miniconda\lib\site-packages\torch\utils\data\dataloader.py", line 560, in __init__
    w.start()
  File "D:\miniconda\lib\multiprocessing\process.py", line 105, in start
    self._popen = self._Popen(self)
  File "D:\miniconda\lib\multiprocessing\context.py", line 223, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "D:\miniconda\lib\multiprocessing\context.py", line 322, in _Popen
    return Popen(process_obj)
  File "D:\miniconda\lib\multiprocessing\popen_spawn_win32.py", line 65, in __init__
    reduction.dump(process_obj, to_child)
  File "D:\miniconda\lib\multiprocessing\reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
_pickle.PicklingError: Can't pickle <function <lambda> at 0x00000264BA7F5598>: attribute lookup <lambda> on testarch.unet.runs failed
[0, 0, 0, 0]

C:\Users\vcvis\Desktop\ature-master>Total Params: 31042434
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "D:\miniconda\lib\multiprocessing\spawn.py", line 105, in spawn_main
    exitcode = _main(fd)
  File "D:\miniconda\lib\multiprocessing\spawn.py", line 115, in _main
    self = reduction.pickle.load(from_parent)
EOFError: Ran out of input

 error might be due to multi threading issue 
where should i modifier for it

**Comment by vcvishal** [comment]
thank you problem solved by setting number of workers =0

**Comment by sraashis** [comment]
Awesome, Thanks for pointing out. I never ran in CPU so hadn't encounter it before.
